version: '3.8'

services:
  bruno-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - CLIENT_ID=${CLIENT_ID}
      - TOKEN=${TOKEN}
      - GUILD_ID=${GUILD_ID}
      - DB_PATH=/app/data/bruno-bot.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
